import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Project",
  description: "Generated by create next app",
};

export default function ProjectsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="pt-[50px]">
        <h1> Project </h1>
        {children}
    </div>

  );
}
